### ISSUE TITLE
Switch to the new REST API

### ISSUE THREAD

**Issue by Elwetana** [JetBrains/YouTrackSharp#100]
Can I ask about the plans for support of the new REST API of YouTrack? Currently we are using the old `/rest/...` interface, but, if I understand it correctly, JetBrains wants to move to the new `/api/...` endpoint. This is obviously a substantial change, is there a plan to do it? Or do you have an insight into the state of development of different REST APIs in YouTrack?

Thanks for any information.

**Comment by maartenba** [comment]
The idea is to work with code generation based on the OpenAPI spec YouTrack provides for the new API.
We are looking at this right now, but no news to share yet. 

Relates to #94

**Comment by Elwetana** [comment]
Alright, thank you.
