### ISSUE TITLE
Discontinuing the Legacy REST API: Action Required

### ISSUE THREAD

**Issue by apuchkov** [JetBrains/YouTrackSharp#104]
Hello,

It seems that this library uses legacy YouTrack API which is being discontinued: 
https://blog.jetbrains.com/youtrack/2021/02/discontinuing-the-legacy-rest-api-action-required/

Are there plans to update this library to use a new API?

Thanks

**Comment by maartenba** [comment]
Hi @apuchkov - check https://blog.jetbrains.com/youtrack/2021/02/discontinuing-the-legacy-rest-api-action-required/#remark42__comment-cff1dd5e-b0bf-4372-809f-80e6e1db6066 for the discussion around this topic.

**Comment by apuchkov** [comment]
Great to know that you are working on a replacement. Looking forward to it. Thanks
