### ISSUE TITLE
2021.3.1 is not working

### ISSUE THREAD

**Issue by kolibaba** [JetBrains/YouTrackSharp#107]
Tying to get issues from YT:
```
var connection = new BearerTokenConnection("https://[some].myjetbrains.com/youtrack", "[token]");
onnection.CreateIssuesService().GetIssues("[filter]", take: 1000);
```
Got error:
```
Unhandled exception. YouTrackSharp.UnauthorizedConnectionException: Could not authenticate. Server did not return expected authentication response. Check the Response property for more details.
   at YouTrackSharp.BearerTokenConnection.GetAuthenticatedApiClient()
   at YouTrackSharp.Issues.IssuesService.GetIssues(String filter, Nullable`1 skip, Nullable`1 take, Boolean wikifyDescription, Boolean wikifyContents)
```

**Comment by kolibaba** [comment]
Token is valid. Tried getting a new token and got the same error

**Comment by rekolobov** [comment]
@kolibaba hi, please check if your token scope is _both_ YouTrack and Hub and re-issue it if it's not so
due to changes in api we had to make this a requirement

see other breaking changes described [here](https://github.com/JetBrains/YouTrackSharp/releases/tag/2021.3.0) in case you missed it

**Comment by kolibaba** [comment]
Can't find scope hub
![image](https://user-images.githubusercontent.com/2988196/126438670-d1fb3a0d-b8f7-4330-8fb9-5e1fe597942f.png)

**Comment by rekolobov** [comment]
apologies,
seems the scope was chosen correctly in your case indeed

could you please check exception's Response property?
assitionally, you could provide your instance name so that I could check server logs if it's required

**Comment by kolibaba** [comment]
{"error":"invalid_token","error_code":401,"error_description":"Token is granted for [YouTrack] and can't be used for 0-0-0-0-0","error_developer_message":"Token is granted for [YouTrack] and can't be used for 0-0-0-0-0"}

**Comment by rekolobov** [comment]
Then generating new token with default selected scopes `YouTrack` and `YouTrack Administration` must help in your case (`0-0-0-0-0` is exactly `YouTrack Administration`)

Note how `Scope Services` should look for a correct token
![screenshot](https://user-images.githubusercontent.com/2941429/126631207-80108e38-6433-40d9-ac98-58d3b02d14db.png)

**Comment by kolibaba** [comment]
Thks, it works now! I used wrong token before, without admin scope.
