### ISSUE TITLE
2021.3.1 Не могу получить поле типа "StateMachineIssueCustomField"

### ISSUE THREAD

**Issue by Klim0o0** [JetBrains/YouTrackSharp#108]
![image](https://user-images.githubusercontent.com/62948134/126483349-752e028f-c46d-4317-a8f2-93f6bce16f6e.png)

Api отдаёт State с типом StateMachineIssueCustomField, а клиент не может спарсить его, по всей видимости ожидая тип "StateIssueCustomField"

добавление в строку 16761 ` [JsonInheritanceAttribute("StateMachineIssueCustomField", typeof(StateIssueCustomField))]`  https://github.com/JetBrains/YouTrackSharp/blob/213/src/YouTrackSharp/Generated/YouTrackSharp.Api.Generated.cs исправляет проблему

**Comment by rekolobov** [comment]
спасибо большое, выпустим билд с исправлением в ближайшие пару дней

**Comment by rekolobov** [comment]
Прошу прощения за задержку, оформил релиз [2021.3.2](https://github.com/JetBrains/YouTrackSharp/releases/tag/2021.3.2), NuGet пакет также опубликован
