### ISSUE TITLE
How to get git commit text for issue id

### ISSUE THREAD

**Issue by dpolivanov** [JetBrains/YouTrackSharp#121]
How can I get the text of a gitLab commit? Does CreateIssuesService not have this option?

**Comment by rekolobov** [comment]
My apologies for the extremely late reply,

We added the ability to retrieve VCS history items as `IssuesService.GetChangeHistoryForIssue("issueId", true)` in [2022.3.1](https://github.com/JetBrains/YouTrackSharp/releases/tag/2022.3.1)

Comments should be accessible now inside VCS activity items.
