### ISSUE TITLE
Cant return customFields

### ISSUE THREAD

**Issue by EzioAuditore01** [JetBrains/YouTrackSharp#126]
Hi,

I am having problem with returning custom fields while using YouTrackSharp method " AdminProjectsIssuesGetAsync".

CustomFields fields is null and also "Begin date".Please see code below.

var res = await client.AdminProjectsIssuesGetAsync("0-6", customFields: "Begin date", fields: "summary,id,description,reporter(fullName)", top: 3);

Returning regular fields works fine.

Thank you in advance.

Best regards,

Boris

**Comment by rekolobov** [comment]
Hello,

`customFileds` param is used to filter out custom fields and leave only the one with matching name.
But respective `fields` query is still required

So a proper way to call this would be
```
var res = await client.AdminProjectsIssuesGetAsync("0-6", customFields: "Begin date", fields: "summary,id,description,reporter(fullName),customFields($type,id,name,value($type,id,name))", top: 3);
```


If you think that we could add some wrapper to `IssuesService` for your convenience, please ping us back

**Comment by EzioAuditore01** [comment]
Hi Roman,

Thank you very much.
That's it :).

**Comment by rekolobov** [comment]
You're welcome! Glad I could help
