### ISSUE TITLE
Extend properties: add `Created` & `Updated` for `TimeTracking.WorkItem`

### ISSUE THREAD

**Issue by jrossgowan-pulsemining** [JetBrains/YouTrackSharp#58]
We are writing a small program with YouTrackSharp which migrates time tracking entries from YouTrack into an external system. I noticed the JSON returned from /rest/issue/*issue id*/timetracking/workitem has *created* and *updated* fields that reflect when each entry was added or modified. These would be pretty useful for us to avoid reimporting work items we have already seen and to identify updates to old work items, but they are not reflected in the .NET TimeTracking.WorkItem class. Could they be added? Any other missing *created* or *updated* fields would also be handy, though I understand that for Issues, they can be retrieved with the GetField() method.

## Expected behavior
- TimeTracking.WorkItem contains Created and Updated members from JSON.

## Actual behavior
- TimeTracking.WorkItem doesn't have Created and Updated members.

## Steps to reproduce the behavior
- Fetch list of WorkItems with TimeTracking.GetWorkItemsForIssue(*issue id*)

**Comment by maartenba** [comment]
Will be in the YouTrackSharp 3.1.0 release.
