### ISSUE TITLE
Provide a strong named version of the library 

### ISSUE THREAD

**Issue by pvandervelde** [JetBrains/YouTrackSharp#6]
At the moment it is not possible to depend on this library if you want to strong name your own libraries because YouTrackSharp isn't strong named so it would be good to have a strong named version.

**Comment by NinjaCross** [comment]
I really like this project, but as of today (8 years after the creation of this issue !), the assembly is still not signed, so it cannot be used in any strong-named context.
Unfortunately, this makes it completely unusable in all my enterprise-related projects.
