### ISSUE TITLE
Add wikifyDescription param to IssuesService.GetIssues()

### ISSUE THREAD

**Issue by jrossgowan-pulsemining** [JetBrains/YouTrackSharp#64]
We are trying to show user-facing descriptions of the issues returned by a specific query, however some issues contain wiki markup, which obscures the content of the description. It would be great if we could use wikifyDescription=true to fetch the description as HTML, so we could use an HTML parser to get a user-facing description of each issue.

## Expected behavior

- IssuesService.GetIssues() accepts the wikifyDescription parameter, like IssuesService.GetIssuesInProject() and the REST API.

## Actual behavior

- IssuesService.GetIssues() does not accept a wikifyDescription parameter.

## Steps to reproduce the behavior

- Call IssuesService.GetIssues("<query>", wikifyDescription: true)

**Comment by maartenba** [comment]
New release is on its way.

**Comment by jrossgowan-pulsemining** [comment]
Thanks for the quick response.
