### ISSUE TITLE
Extend class User with RingId property

### ISSUE THREAD

**Issue by aschoelzhorn** [JetBrains/YouTrackSharp#67]
## Expected behavior
ringId from response is mapped to property Id of User

## Actual behavior
no property Id in class user

**Comment by maartenba** [comment]
For which operation is this?

**Comment by maartenba** [comment]
Nevermind, adding this.

**Comment by maartenba** [comment]
See https://github.com/JetBrains/YouTrackSharp/releases/tag/3.2.3
