### ISSUE TITLE
How do you specify that a new issue description is in Markdown format?

### ISSUE THREAD

**Issue by Tenebrous** [JetBrains/YouTrackSharp#74]

**Comment by maartenba** [comment]
The API currently does not support this. Will check with the YouTrack folks if this is possible.
Which version of YouTrack are you using?

**Comment by maartenba** [comment]
Just pushed a fresh version that supports Markdown. Check the `IsMarkdown` property on issue/comment objects.

**Comment by Tenebrous** [comment]
Awesome, thanks!

**Comment by Tenebrous** [comment]
Sorry... but we're on YouTrack InCloud 2018.1 and I get the following exception when I create an issue:
`Command [markdown True] is invalid:Unknown command: unknown command: markdown True`

> JetBrains Bug & Issue Tracker YouTrack 2018.1
> Build 41051 18/04/18 22:00
