### ISSUE TITLE
issue.GetField("Assignee").AsCollection() returns a List<string> with "System.Collections.Generic.List`1[YouTrackSharp.Issues.Assignee]", rather than the actual Assignee name

### ISSUE THREAD

**Issue by MarkHutchings** [JetBrains/YouTrackSharp#76]
See:
https://github.com/JetBrains/YouTrackSharp/blob/c591920981c9e0b8a4717856934be281b27251ad/src/YouTrackSharp/Issues/Field.cs#L71

**Comment by MarkHutchings** [comment]
Just one!

**Comment by MarkHutchings** [comment]
For now I'm doing: (List<Assignee>)issue.GetField("Assignee").Value - perhaps that's the preferred solution?

**Comment by maartenba** [comment]
You can just get the `issue.Assignee[0]` as well.

**Comment by MarkHutchings** [comment]
Ah, that works if the type is dynamic (i.e. issue.AsDynamic().Assignee[0]).
