### ISSUE TITLE
UsernamePasswordConnection missing?

### ISSUE THREAD

**Issue by Jaben** [JetBrains/YouTrackSharp#86]
## Expected behavior

'UsernamePasswordConnection' is referenced in the readme -- but it doesn't appear to exist.

## Actual behavior

It's supported in addition to BearerTokenConnection

## Steps to reproduce the behavior

Try to use UsernamePasswordConnection.

**Comment by maartenba** [comment]
This is no longer supported in 2019.1. Older versions still have it available.

**Comment by maartenba** [comment]
Updated README, good catch.
