### ISSUE TITLE
Define content-type header in IssuesService.AttachFileToIssue

### ISSUE THREAD

**Issue by bouil** [JetBrains/YouTrackSharp#87]
Using YouTrackSharp 2019.1.0.0

## Expected behavior

- Using IssueService.AttachFileToIssue with an XLSX file.
- Document is uploaded.
- When downloading the file from Youtrack, it's expected to be able to have the correct content type header 

## Actual behavior

- File is served as a ZIP file.

## Possible fix ?

Allow uploader to specify content type in the MultipartFormDataContent object in the AttachFileToIssue metehod

**Comment by maartenba** [comment]
Fixed (pending validation on NuGet.org)

**Comment by bouil** [comment]
Thanks, I confirm that you commit fixes the issue.
