### ISSUE TITLE
UserManagementService .CreateUser replaces ' ' with '%20'

### ISSUE THREAD

**Issue by FinkoAI** [JetBrains/YouTrackSharp#90]
## Expected behavior
There is still an issue in POST/PUT requests. It is linked to the #89.
## Actual behavior
 Currentlu it replaces spaces in string with the space escape code '%20'. I guess the reason is escaping strings for FromData requests. In case of POST/PUT data could be sent as is, because of sending in request body, but not in the URL

**Comment by maartenba** [comment]
Thanks! Fix is on its way to NuGet
