### ISSUE TITLE
UserManagementService .CreateUser replaces '@' with '%40'

### ISSUE THREAD

**Issue by CyrilCoq** [JetBrains/YouTrackSharp#91]
## Expected behavior
The email address should be valid and as entered with the @ sign

## Actual behavior
The email address has the @ sign replaced by %40

## Steps to reproduce the behavior
Create new user with an email address and it will "Encode" it.
Same as issue #90 I believe we need to leave the string as is, no encoding since it will be be re-encoded in the body somehow.

**Comment by maartenba** [comment]
Thanks, just pushed a fresh one. Password is still being encoded for now

**Comment by CyrilCoq** [comment]
Thank you for your reactivity !
