### ISSUE TITLE
IsMarkDown on case creation not fully implemented

### ISSUE THREAD

**Issue by CyrilCoq** [JetBrains/YouTrackSharp#92]
## Expected behavior
When using IsMarkDown = false it should create a case without the Markdown option ( YouTrack Wiki ). The Querystring sent to YT should show markdown=false.

## Actual behavior
Nothing is appended to the QueryString when using IsMarkDown = false. ( only appended when IsMarkDown = true )

## Steps to reproduce the behavior
Create an issue and use IsMarkDown = false, the querystring is not appeneded and the Case is created with the default value to MarkDown.

Potential fix on or around:  "if (issue.IsMarkdown)" on line 97 of IssueService.cs

**Comment by maartenba** [comment]
Good catch! Let me see if I can get that fixed.

**Comment by maartenba** [comment]
New release should be up shortly.

**Comment by CyrilCoq** [comment]
Thank you :)
