### ISSUE TITLE
Field names ignore case: why?

### ISSUE THREAD

**Issue by Elwetana** [JetBrains/YouTrackSharp#98]
The current implementation parses JSON from server while ignoring the case of field names. This behaviour is AFAIK implemented in file `Issues/Issue.cs` on line 22:

````C#
private readonly IDictionary<string, Field> _fields = new Dictionary<string, Field>(StringComparer.OrdinalIgnoreCase);
````

I am not sure why we have this behaviour -- JSON is case-sensitive and YouTrack can have two different fields that only differ in case (in my case it was fields `Sprint` and `sprint`). I was able to fix it by simply changing the comparer to  `StringComparer.Ordinal`. I would be very happy to submit this simple change as pull request, or am I missing something? 

Thank you.

**Comment by maartenba** [comment]
No idea what the reason was there to be honest. Might be OK to update it.
